# Generated by Django 5.2.6 on 2025-09-19 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_sale_payment_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='category',
            field=models.CharField(choices=[('Pain Relief & Anti-inflammatory', 'Pain Relief & Anti-inflammatory'), ('Antibiotics', 'Antibiotics'), ('Cold & Flu', 'Cold & Flu'), ('Stomach & Digestive', 'Stomach & Digestive'), ('Blood Pressure & Heart', 'Blood Pressure & Heart'), ('Diabetes', 'Diabetes'), ('Vitamins & Supplements', 'Vitamins & Supplements'), ("Women's Health", "Women's Health"), ('Topical/External', 'Topical/External')], default='Pain Relief & Anti-inflammatory', max_length=50),
            preserve_default=False,
        ),
    ]
