# Generated by Django 5.0.6 on 2025-09-19 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_medicine_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='category',
        ),
    ]
